### ISSUE TITLE
Editor tab doesn't work on Firefox

### ISSUE THREAD

**Issue by Dikower** [fouita/tailwind-editor#1]
I don't know if it's a bug of library. But it doesn't show editor tab in Firefox, when I select a text. But in Yandex Browser/Chrome it works well.
![изображение](https://user-images.githubusercontent.com/25639843/98100190-913a0a00-1ea1-11eb-87d3-6af2e6bd86e1.png)

**Comment by haynajjar** [comment]
Thanks for pointing that out, fixed on version 0.0.6 for firefox
