### ISSUE TITLE
remove previous class before adding a new one

### ISSUE THREAD

**Issue by giosifelis** [fouita/tailwind-editor#3]
Hello,  

first of all congrats on your work.  I like that it keeps a clean html.

Here is what i've noticed.  When I add a background color or bg-transparent or a text color, and then I change the color, the editor just adds the new class that i selected.  Therefore it ends up having multiple text- or bg- classes, for example:

`<span class="text-teal-600 text-white text-black text-red-400 bg-blue-500 bg-transparent">style</span>`

if a text- class is selected it should delete all other text- classes.  the same with the bg- class. in other words, there should be  only one text- or bg- class at any given time. 

cheers

**Comment by haynajjar** [comment]
Thank you for pointing that out, it was an issue with "teal" ,"white" and "black" colors, i updated a quick fix with the version 0.0.7

**Comment by giosifelis** [comment]
Nice. The white and black classes are working perfect now.

 I also noticed the same issue with the bg-transparent class.  When it is applied, all other bg- classes should be removed because they overwrite the bg-transparent class.

**Comment by haynajjar** [comment]
You are right, i forgot about the transparent, it should work fine now with 0.0.8
