### ISSUE TITLE
Editor pops far away from the content 

### ISSUE THREAD

**Issue by acarnage** [fouita/tailwind-editor#4]
Hello,

I am having issues using your component :

![image](https://user-images.githubusercontent.com/7127000/107363425-6c75b400-6ada-11eb-9123-4c2903d8a9e2.png)

As you can see in the image, the editing popup pops really far away from the content I desire to edit. Do you have an idea about how I can fix this ?

following is the implemented (revelent) code : 
`<div class="p-4 whitespace-pre-wrap">
            <div class="relative flex">
                <Editor bind:html={html} {arr_html} />
                <div>
                    {html}
                </div>
            </div>
        </div>`

Thanks you !

EDIT : The problem seems to be that i have an element with the "relative" class higher in the DOM tree, conflicting with the positioning of the toolbar.

**Comment by haynajjar** [comment]
there was an issue if the parent element has relative position, It is fixed it on the new version 0.0.9
